### ISSUE TITLE
Noise

### ISSUE THREAD

**Issue by crewl2** [open-ephys/low-profile-spi-headstage-64ch#1]
I'm getting a ton of noise, I'm wondering if it is coming from the headstage. Should the headstage be grounded?

**Comment by jonnew** [comment]
Hi. Yes, it will need to be grounded in order to complete the electrical circuit. I'm not trying to be rude, but you question is indicates that you might need some help setting up your system and understanding the basics of extracellular recordings. I would have a look through this excellent set of materials put together by @ahleighton on how ephys works https://ahleighton.github.io/OE-ephys-course/EEA/theoryday1.html. Also if there is somebody in your lab that has done this type of recording before, I would talk with them about your issue.
